#!/usr/bin/env bash

cd ../deploy

./gameboy GAMECARD GET_POKEMON SHAQUILLE 100
./gameboy GAMECARD GET_POKEMON SHAQUILLE 101
./gameboy GAMECARD GET_POKEMON SHAQUILLE 102
./gameboy GAMECARD GET_POKEMON SHAQUILLE 103
./gameboy GAMECARD GET_POKEMON SHAQUILLE 104
./gameboy GAMECARD GET_POKEMON SHAQUILLE 105
./gameboy GAMECARD GET_POKEMON SHAQUILLE 106
./gameboy GAMECARD GET_POKEMON SHAQUILLE 107
./gameboy GAMECARD GET_POKEMON SHAQUILLE 108
./gameboy GAMECARD GET_POKEMON SHAQUILLE 109
